import Head from 'next/head';
import styles from '@/styles/Home.module.css';

export default function Home() {
    return (
        <>
            <Head>
                <title>Touch Typing Academy</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className={styles.main}>
                <div className={styles.description}>
                    <div className={styles.banner}>Banner</div>
                    <div className={styles.cards}>Cards</div>
                    <div className={styles.info}>Information</div>
                    <div className={styles.reviews}>Reviews</div>
                </div>
            </main>
        </>
    );
}
